version: "3.8"

services:
    edc_landing_django:
        container_name: edc_landing_django
        build: .
        volumes:
            - ./:/code/
            - ./docker/landing/static:/code/static
        env_file:
            - .env

    edc_landing_nginx:
        container_name: edc_landing_nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/landing/static:/code/static
        depends_on:
            - edc_landing_django
        environment:
            - VIRTUAL_HOST=${SERVICE_LANDING_DNS}
            - LETSENCRYPT_HOST=${SERVICE_LANDING_DNS}
            - LETSENCRYPT_EMAIL=${SSL_LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: edcNet
