version: "3.3"

services:
    landing_psql:
        container_name: landing_psql
        image: postgres
        restart: always
        ports:
            - ${APP_DB_PORT:-5432}:5432
        volumes:
            - landingPsqlVolume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${APP_DB_NAME:-landing}
            POSTGRES_USER: ${APP_DB_USER:-admin}
            POSTGRES_PASSWORD: ${APP_DB_PASS:-secret}
        networks:
            - landingNet

    landing_django:
        container_name: landing_django
        build: .
        volumes:
            - ./:/code
            - ./docker/landing/static:/code/static
        depends_on:
            - landing_psql
        environment:
            APP_ENV: ${APP_ENV:-dev}
        networks:
            - landingNet

    landing_nginx:
        container_name: landing_nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/landing/static:/code/static
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - landing_django
        networks:
            - landingNet

    landing_redis:
        container_name: landing_redis
        image: redis:6
        restart: always
        networks:
            - landingNet

networks:
    landingNet:
        driver: "bridge"

volumes:
    landingPsqlVolume:
