version: "3.3"

services:
    edc_psql:
        container_name: edc_psql
        image: postgres
        restart: always
        ports:
            - ${APP_DB_PORT:-5432}:5432
        volumes:
            - psqlVolume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${APP_DB_NAME:-mobilender}
            POSTGRES_USER: ${APP_DB_USER:-mobilender}
            POSTGRES_PASSWORD: ${APP_DB_ROOT_PSW:-secret}
        networks:
            - edciloNet

    edc_django:
        container_name: edc_django
        build: .
        volumes:
            - ./:/code
        depends_on:
            - edc_psql
        environment:
            APP_ENV: ${APP_ENV:-dev}
        networks:
            - edciloNet

    edc_nginx:
        container_name: edc_nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - edc_django
        networks:
            - edciloNet

networks:
    edciloNet:
        driver: "bridge"

volumes:
    psqlVolume:
