# Generated by Django 3.1.3 on 2020-11-13 03:30

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Schema's name")),
                ('schema', models.JSONField(default=landingpage.models.schema_default, help_text='JSON schema')),
                ('published', models.BooleanField(default=False, help_text='Use this schema?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing schema',
                'ordering': ['-last_modified'],
                'get_latest_by': 'created',
            },
        ),
    ]
